baseURL = "http://tangzero.com"
languageCode = "pt-br"
title = "TangZero | Blog"
theme = "minimo"
disqusShortname = "tangzero"
googleAnalytics = "UA-101783674-1"
pygmentsuseclasses = true

[taxonomies]
  tag = "tags"
  category = "categorias"

[params]
  description = "Meu cantinho para falar de tecnologia"
  dateFormat = "02/01/2006"
  copyrightOwner = "TangZero"
  copyrightStartYear = "2017"
  favicon = "favicon.ico"
  hideEntryNavigation = true
  customCSS = ["css/styles.css", "css/syntax-highlight.css"]

[social]
  facebook = ""

[author]
  name = "Jairo Luiz"

[author.social]
  github = "tangzero"
  twitter = "tangzero"

[[menu.main]]
  name = "Home"
  weight = -70
  identifier = "home"
  url = "/"

defaultContentLanguage = "pt"
[languages]
  [languages.pt]
    lang = "pt"
    languageName = "Portuguese"
    weight = 1
